"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
exports.Parse = void 0;
var Parse;
(function (Parse) {
    Parse["everyone"] = "everyone";
    Parse["users"] = "users";
    Parse["roles"] = "roles";
})(Parse = exports.Parse || (exports.Parse = {}));
